Vagrant.configure("2") do |config|
  # Use a box known for excellent libvirt compatibility
  config.vm.box = "generic/debian12"
  
  # Set libvirt as the default provider for this project
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

  # Jumpbox Node
  config.vm.define "server" do |node|
    node.vm.hostname = "server"
    node.vm.network "private_network", ip: "10.240.0.10"
    node.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 1
    end
  end

  # Worker Node
  config.vm.define "node-0" do |node|
    node.vm.hostname = "node-0"
    node.vm.network "private_network", ip: "10.240.0.20"
    node.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 1
    end
  end

  config.vm.define "node-1" do |node|
    node.vm.hostname = "node-1"
    node.vm.network "private_network", ip: "10.240.0.21"
    node.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 1
    end
  end
end